### ISSUE TITLE
Increase Pod timeout for serving CI job(s)

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2518]
See [slack](https://knative.slack.com/archives/CCSNR4FCH/p1603128725239100)

We need to add to the job(s):
```
    decoration_config:
        timeout: 3h
```

i.e. [this job](https://github.com/knative/test-infra/blob/d236fb0ea9ffd3c6e9fba6b2ad19ec9987315260/config/prod/prow/jobs/config.yaml#L4189) would start with this instead:

```
  name: ci-knative-serving-continuous
  agent: kubernetes
  decorate: true
  decoration_config:
    timeout: 3h
  cluster: "build-knative"
```

Will probably require modifying [this](https://github.com/knative/test-infra/tree/master/tools/config-generator).

cc @joshua-bone @dprotaso
