### ISSUE TITLE
Deployment of the ExternalSecret for the Prow job 'ci-knative-eventing-s390x-e2e-tests'

### ISSUE THREAD

**Issue by BbolroC** [knative/test-infra#2775]
In order to get the prow job `ci-knative-eventing-s390x-e2e-tests` to reach the s390x test machine, the relevant secret has been updated by one of the maintainers (thanks @coryrc) on the knative build cluster (see https://github.com/knative/test-infra/pull/2717#pullrequestreview-617991296)
But, the [kubernetes external secret](https://github.com/external-secrets/kubernetes-external-secrets) has been recently installed thanks to @chaodaiG (see https://github.com/GoogleCloudPlatform/oss-test-infra/pull/807) on the cluster.

I would like to update the secret through the external secret whenever I want. I have finished the following steps (up until the 2nd at the client side at https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md):

- The secrets are created on the GCP secret manager. 
- The IAM policies `roles/secretmanager.secretAccessor` and `roles/secretmanager.viewer` are granted to `serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com` for the access of the secrets 

I would like to ask about the final step of where to place the yaml file below in this repo:

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: s390x-cluster1
  namespace: knative-tests
spec:
  backendType: gcpSecretsManager
  projectId: s390x-knative
  data:
  - key: kubeconfig
    name: config
    version: latest
  - key: ko-docker-repository
    name: ko-docker-repo
    version: latest
  - key: registry-certificate
    name: registry.crt
    version: latest
```

Thank you very much.
