### ISSUE TITLE
Run knative tests on ppc64le architecture

### ISSUE THREAD

**Issue by Siddhesh-Ghadi** [knative/test-infra#2842]
This issue describes the approach using which knative can be tested on `ppc64le` architecture similar to `s390x`. We will follow similar approach describe in #2717.
> The idea that main job is running on Intel architecture, as any other standard test job, but the actual tests will be executed on another k8s arch-specific cluster.

#### Approach
1. Fetch helper script from remote `ppc64le` machine to setup k8s cluster.
2. Run helper script which will spin up a `ppc64le` k8s cluster & setup kubeconfig & private registry files for access.
3. Run knative e2e tests.

`secret: ppc64le-cluster` will contain
- `private-key` for ssh access to `ppc64le` hardware.
- `config` will contain remote `ppc64le` machine IP.
- `ko-docker-repo` secret environment value for `KO_DOCKER_REPO`.

For `ppc64le`, we don't have a kind based k8s cluster supported yet however, we can quickly spin up k8s cluster using `kubeadm` on per-created `ppc64le` vms at ibm-cloud. 

I have tested following job configuration for `knative/eventing` e2e test using `mkpj` and `phaino` tools on a `x86` node and actual test running on `ppc64le` k8s cluster.
```yaml
  - custom-job: ppc64le-e2e-tests
    cron: 0 7 * * *
    command:
    - bash
    args:
    - -c
    - >-
      server_addr=$(cat /opt/cluster/config) &&
      scp -i /opt/cluster/knative.pem -o StrictHostKeyChecking=no root@${server_addr}:/root/data/share/cluster-setup.sh /tmp &&
      . /tmp/cluster-setup.sh && 
      ./test/e2e-tests.sh --run-tests
    env-vars:
    - DISABLE_MD_LINTING="1"
    - KO_FLAGS="--platform=linux/ppc64le"
    - DEPLOY_KNATIVE_MONITORING="0"
    - SYSTEM_NAMESPACE="knative-eventing"
    - PLATFORM="linux/ppc64le"
    - KUBECONFIG="/root/.kube/config"
    - SCALE_CHAOSDUCK_TO_ZERO="1"
    external_cluster:
      secret: ppc64le-cluster
```

I would like to know community's thoughts on this. Thanks
