### ISSUE TITLE
Switch to using ArgoCD to deploy cluster manifests instead of `kubectl`

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3363]
When changes to the cluster configuration is made, a prow postsubmit job runs `kubectl apply -f prow/cluster/build` to deploy the config, but this problematic for a few reasons:

- No pruning support. I deleted a Service in #3360 but it still around and requires manual cleanup by a human
- It is kind of slow: https://prow.knative.dev/view/gs/knative-prow/logs/post-test-infra-deploy-prow/1532834481885417472
- Resource apply order complexity.
- Using helm charts is messy. Someone needs to do `$ helm template --include-crds --output-dir ./output_dir external-secrets/kubernetes-external-secrets` instead of 
```
# Random Example
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-prod
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    name: prod
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
      - name: installCRDs
        value: "true"
      releaseName: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.6.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```
- Updating third party tools loaded via Helm will be simpler in addition to leaner config.

/cc @kvmware 

If we are happy with this, let me know and i'll bootstrap argocd in the prow cluster.
