### ISSUE TITLE
SLSA 1 Compliance

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3440]
https://slsa.dev/spec/v0.1/requirements

For SLSA 1 we need to do the following:

- Build:
  - ~~Scripted Build: All build steps were fully defined in some sort of “build script”. The only manual command, if any, was to invoke the build script.~~ ✅ 
- Provenance:
  - Available: The provenance is available to the consumer in a format that the consumer accepts. The format SHOULD be in-toto [SLSA Provenance](https://slsa.dev/provenance), but another format MAY be used if both producer and consumer agree and it meets all the other requirements. I'm thinking of just attesting the SBOMs generated by `ko` by running `cosign attest --predicate sbom.json --key gcpkms://projects/knative-nightly/locations/global/keyRings/cosign/cryptoKeys/signing-key gcr.io/knative-nightly/knative.dev/container-freezer/cmd/daemon` as an example.
  - Identifies the artifact: The provenance MUST identify the output artifact via at least one cryptographic hash. The provenance MAY provide multiple identifying cryptographic hashes using different algorithms. When only one hash is provided, the RECOMMENDED algorithm is SHA-256 for cross-system compatibility. If another algorithm is used, it SHOULD be resistant to collisions and second preimages.
  - Identifies the builder: The provenance identifies the entity that performed the build and generated the provenance. This represents the entity that the consumer must trust. Examples: “GitHub Actions with a GitHub-hosted worker”, “[jdoe@example.com](mailto:jdoe@example.com)’s machine”.
  - Identifies the build instructions: The provenance identifies the top-level instructions used to execute the build. The identified instructions SHOULD be at the highest level available to the build (e.g. if the build is told to run build.sh it should list build.sh and NOT the individual instructions in build.sh).
   
/kind security
/priority important-soon

**Comment by upodroid** [comment]
@mattmoor 

I'm having a hardtime working out the Provenance piece.

Using net-certmanager as an example.

To build images, we call https://github.com/knative-sandbox/net-certmanager/blob/main/vendor/knative.dev/hack/release.sh and https://github.com/knative-sandbox/net-certmanager/blob/main/hack/release.sh.

A typical run looks like this. https://storage.googleapis.com/knative-prow/logs/nightly_net-certmanager_main_periodic/1550767763880939520/build-log.txt

If I supply the sbom as predicate and run `cosign attest --predicate sbom.json --key gcpkms://projects/knative-nightly/locations/global/keyRings/cosign/cryptoKeys/signing-key gcr.io/knative-nightly/knative.dev/container-freezer/cmd/daemon` it only meets half of the requirements and I get an attestation that looks like this:

```yaml
---
_type: https://in-toto.io/Statement/v0.1
predicateType: cosign.sigstore.dev/attestation/v1
subject:
- name: gcr.io/knative-nightly/knative.dev/container-freezer/cmd/daemon
  digest:
    sha256: '06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70'
predicate:
  Data: |
    {
      "SPDXID": "SPDXRef-DOCUMENT",
      "name": "sbom-sha256:06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
      "spdxVersion": "SPDX-2.2",
      "creationInfo": {
        "created": "2022-07-23T02:16:23Z",
        "creators": [
          "Tool: ko v0.11.3-0.20220715180928-3d362cf6702f"
        ]
      },
      "dataLicense": "CC0-1.0",
      "documentNamespace": "http://spdx.org/spdxdocs/ko/sha256:06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
      "documentDescribes": [
        "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70"
      ],
      "packages": [
        {
          "SPDXID": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "name": "sha256:06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/index@sha256:06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70?mediaType=application%2Fvnd.oci.image.index.v1%2Bjson",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-683737dbc197ac24fae46b4fc0b9bca0dabc495ff2bd0bbe8334e97685d91b2c",
          "name": "ghcr.io/distroless/static@sha256:683737dbc197ac24fae46b4fc0b9bca0dabc495ff2bd0bbe8334e97685d91b2c",
          "versionInfo": "ghcr.io/distroless/static:latest",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "683737dbc197ac24fae46b4fc0b9bca0dabc495ff2bd0bbe8334e97685d91b2c"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:683737dbc197ac24fae46b4fc0b9bca0dabc495ff2bd0bbe8334e97685d91b2c?repository_url=ghcr.io%2Fdistroless%2Fstatic\u0026tag=latest",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-5c435970807e375629d1212ab22a77f63febe7ee9562050cf9ef08faa59f6538",
          "name": "sha256:5c435970807e375629d1212ab22a77f63febe7ee9562050cf9ef08faa59f6538",
          "versionInfo": "linux/386",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "5c435970807e375629d1212ab22a77f63febe7ee9562050cf9ef08faa59f6538"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:5c435970807e375629d1212ab22a77f63febe7ee9562050cf9ef08faa59f6538?arch=386\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-3db31766df168607a4841ac8d785b7d1e6249df42a9463bb68be1832e3e05f5e",
          "name": "sha256:3db31766df168607a4841ac8d785b7d1e6249df42a9463bb68be1832e3e05f5e",
          "versionInfo": "linux/amd64",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "3db31766df168607a4841ac8d785b7d1e6249df42a9463bb68be1832e3e05f5e"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:3db31766df168607a4841ac8d785b7d1e6249df42a9463bb68be1832e3e05f5e?arch=amd64\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-5f62eb2d4c266818bc00d6e1b59a23a07232c0e55fd936f444ab4a1ea34d94e5",
          "name": "sha256:5f62eb2d4c266818bc00d6e1b59a23a07232c0e55fd936f444ab4a1ea34d94e5",
          "versionInfo": "linux/arm/v6",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "5f62eb2d4c266818bc00d6e1b59a23a07232c0e55fd936f444ab4a1ea34d94e5"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:5f62eb2d4c266818bc00d6e1b59a23a07232c0e55fd936f444ab4a1ea34d94e5?arch=arm\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux\u0026variant=v6",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-ba0959c87fc72ef00beb4af63ec93022cbf3a2057a55684c71b7ef267f774e3f",
          "name": "sha256:ba0959c87fc72ef00beb4af63ec93022cbf3a2057a55684c71b7ef267f774e3f",
          "versionInfo": "linux/arm/v7",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "ba0959c87fc72ef00beb4af63ec93022cbf3a2057a55684c71b7ef267f774e3f"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:ba0959c87fc72ef00beb4af63ec93022cbf3a2057a55684c71b7ef267f774e3f?arch=arm\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux\u0026variant=v7",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-7cc2080eed1a84179c353807169fdc09ca0866c1c219c9c138170b375132925b",
          "name": "sha256:7cc2080eed1a84179c353807169fdc09ca0866c1c219c9c138170b375132925b",
          "versionInfo": "linux/arm64",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "7cc2080eed1a84179c353807169fdc09ca0866c1c219c9c138170b375132925b"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:7cc2080eed1a84179c353807169fdc09ca0866c1c219c9c138170b375132925b?arch=arm64\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-5f920b8fbc8ec2194966af61eb78ead3407b20c50d774489eb6d42ed6e1ced01",
          "name": "sha256:5f920b8fbc8ec2194966af61eb78ead3407b20c50d774489eb6d42ed6e1ced01",
          "versionInfo": "linux/ppc64le",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "5f920b8fbc8ec2194966af61eb78ead3407b20c50d774489eb6d42ed6e1ced01"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:5f920b8fbc8ec2194966af61eb78ead3407b20c50d774489eb6d42ed6e1ced01?arch=ppc64le\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-93b6f1a2fe540a515ca06b23c65847371fb2e58790734d7042677991554f535d",
          "name": "sha256:93b6f1a2fe540a515ca06b23c65847371fb2e58790734d7042677991554f535d",
          "versionInfo": "linux/riscv64",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "93b6f1a2fe540a515ca06b23c65847371fb2e58790734d7042677991554f535d"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:93b6f1a2fe540a515ca06b23c65847371fb2e58790734d7042677991554f535d?arch=riscv64\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        },
        {
          "SPDXID": "SPDXRef-Package-sha256-ac4bcb7d1a2b83f42bb367b5d4cb45f81f3844dd889cb8c5721fab2a21cc3af2",
          "name": "sha256:ac4bcb7d1a2b83f42bb367b5d4cb45f81f3844dd889cb8c5721fab2a21cc3af2",
          "versionInfo": "linux/s390x",
          "filesAnalyzed": false,
          "licenseDeclared": "NOASSERTION",
          "licenseConcluded": "NOASSERTION",
          "downloadLocation": "NOASSERTION",
          "copyrightText": "NOASSERTION",
          "checksums": [
            {
              "algorithm": "SHA256",
              "checksumValue": "ac4bcb7d1a2b83f42bb367b5d4cb45f81f3844dd889cb8c5721fab2a21cc3af2"
            }
          ],
          "externalRefs": [
            {
              "referenceCategory": "PACKAGE_MANAGER",
              "referenceLocator": "pkg:oci/image@sha256:ac4bcb7d1a2b83f42bb367b5d4cb45f81f3844dd889cb8c5721fab2a21cc3af2?arch=s390x\u0026mediaType=application%2Fvnd.oci.image.manifest.v1%2Bjson\u0026os=linux",
              "referenceType": "purl"
            }
          ]
        }
      ],
      "relationships": [
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "DESCENDANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-683737dbc197ac24fae46b4fc0b9bca0dabc495ff2bd0bbe8334e97685d91b2c"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-5c435970807e375629d1212ab22a77f63febe7ee9562050cf9ef08faa59f6538"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-3db31766df168607a4841ac8d785b7d1e6249df42a9463bb68be1832e3e05f5e"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-5f62eb2d4c266818bc00d6e1b59a23a07232c0e55fd936f444ab4a1ea34d94e5"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-ba0959c87fc72ef00beb4af63ec93022cbf3a2057a55684c71b7ef267f774e3f"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-7cc2080eed1a84179c353807169fdc09ca0866c1c219c9c138170b375132925b"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-5f920b8fbc8ec2194966af61eb78ead3407b20c50d774489eb6d42ed6e1ced01"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-93b6f1a2fe540a515ca06b23c65847371fb2e58790734d7042677991554f535d"
        },
        {
          "spdxElementId": "SPDXRef-Package-sha256-06846e64a6b6e954df9a8253ad9a2fa62b81a5b8e960f38a258ced50b9366d70",
          "relationshipType": "VARIANT_OF",
          "relatedSpdxElement": "SPDXRef-Package-sha256-ac4bcb7d1a2b83f42bb367b5d4cb45f81f3844dd889cb8c5721fab2a21cc3af2"
        }
      ]
    }
  Timestamp: '2022-07-23T11:18:34Z'

```
